GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
  "username": "Tsest", 
  "password": "Test",
  "skillCoins": 0
}
###
PUT http://localhost:3001/api/users/646d22ce2ba2595c59c3f318 HTTP/1.1
content-type: application/json

{
  "username": "Saransh",
  "password": "amogus",
  "seqNScore": 0,
  "seqCScore": 0,
  "scramNScore": 0,
  "scramCScore": 0,
  "skillCoins": 0
}