GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
  "username": "Joe Biden", 
  "password": "America",
  "seqNScore": 3
}
###
PUT https://skillcheck-backend.onrender.com/api/users/646c46342a755d4c3cb8159d HTTP/1.1
content-type: application/json

{
  "username": "Saransh",
  "password": "amogus",
  "seqNScore": 0,
  "seqCScore": 0,
  "scramNScore": 0,
  "scramCScore": 0,
  "id": "646c46342a755d4c3cb8159d"
}